name: Send Email with Attachment

on:
  workflow_dispatch: 

jobs:
  send_email:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Send email
        uses: dawidd6/action-send-mail@v3.12.0
        with:
          server_address: 	mail.ustc.edu.cn
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }} 
          password: ${{ secrets.EMAIL_PASSWORD }} 
          subject: "dailyprint"
          from: ${{ secrets.EMAIL_USERNAME }} 
          to: ${{ secrets.EMAIL_ADDRESS }} 
          attachments: "lines.docx"
