name: Send Email with Attachment

on:
  schedule:
    - cron: '30 19 * * *' 
  workflow_dispatch: 

jobs:
  send_email:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Calculate file index
        id: calculate
        run: |
          DAY_INDEX=$(( ( $(date +%s) / 86400 ) % 45 + 1 ))
          echo "DAY_INDEX=${DAY_INDEX}" >> $GITHUB_ENV
          FILE_NAME="p${DAY_INDEX}.txt"
          echo "FILE_NAME=${FILE_NAME}" >> $GITHUB_ENV

      - name: Send email
        uses: dawidd6/action-send-mail@v3.12.0
        with:
          server_address: smtp.office365.com  
          server_port: 587  
          username: ${{ secrets.EMAIL_USERNAME }} 
          password: ${{ secrets.EMAIL_PASSWORD }} 
          subject: "Daily Attachment: ${{ env.FILE_NAME }}"
          to: listen04@hotmail.com
          attachments: ${{ env.FILE_NAME }}
